import type { Config } from "@docusaurus/types";

const isNext = process.env.CHANNEL === "next";

// allow baseUrl override per channel (stable=/, next=/next/)
const baseUrl = isNext ? "/next/" : "/";

const config: Config = {
  title: "The Miden Book",
  tagline: "One stop shop for everything Miden",
  favicon: "img/favicon.ico",

  url: "https://0xmiden.github.io/",
  baseUrl,

  organizationName: "0xMiden",
  projectName: "miden-docs",

  onBrokenLinks: "warn",
  onBrokenMarkdownLinks: "warn",

  i18n: {
    defaultLocale: "en",
    locales: ["en"],
  },

  presets: [
    [
      "classic",
      /** @type {import('@docusaurus/preset-classic').Options} */
      {
        docs: false, // Disable preset docs plugin => using own plugin
        blog: false, // Disable blog
        theme: {
          // customCss: "./src/css/custom.css",
        },
      },
    ],
  ],

  themes: ["@docusaurus/theme-mermaid"],

  // enable mermaid diagrams and math support
  markdown: {
    mermaid: true,
  },

  plugins: [
    // Single docs instance containing all content
    [
      "@docusaurus/plugin-content-docs",
      {
        // Single global docs root
        path: "docs",
        routeBasePath: "/", // site lives at /
        sidebarPath: "./sidebars.ts", // use autogenerated
      },
    ],
  ],

  themeConfig:
    /** @type {import('@docusaurus/preset-classic').ThemeConfig} */
    {
      navbar: {
        title: "Miden",
        items: [
          {
            href: "https://github.com/0xPolygonMiden/",
            label: "GitHub",
            position: "right",
          },
        ],
      },
    },
};

export default config;
