import type { Config } from "@docusaurus/types";
import remarkMath from "remark-math";
import rehypeKatex from "rehype-katex";

const isNext = process.env.CHANNEL === "next";

const config: Config = {
  title: "The Miden Book",
  tagline: "One stop shop for everything Miden",
  favicon: "img/favicon.ico",

  url: "https://0xmiden.github.io/",
  baseUrl: "/",

  organizationName: "0xMiden",
  projectName: "miden-docs",

  onBrokenLinks: "warn",
  onBrokenMarkdownLinks: "warn",

  i18n: {
    defaultLocale: "en",
    locales: ["en"],
  },

  presets: [
    [
      "classic",
      /** @type {import('@docusaurus/preset-classic').Options} */
      {
        docs: {
          // Single global docs root
          routeBasePath: "/", // site lives at /
          sidebarPath: "./sidebars.ts", // use autogenerated,
          includeCurrentVersion: true,
          versions: {
            current: {
              label: "Next",
            },
          },
          remarkPlugins: [remarkMath],
          rehypePlugins: [rehypeKatex],
        }, // Disable preset docs plugin => using own plugin
        blog: false, // Disable blog
        theme: {
          // customCss: "./src/css/custom.css",
        },
      },
    ],
  ],

  stylesheets: [
    {
      href: "https://cdn.jsdelivr.net/npm/katex@0.13.24/dist/katex.min.css",
      type: "text/css",
      integrity:
        "sha384-odtC+0UGzzFL/6PNoE8rX/SPcQDXBJ+uRepguP4QkPCm2LBxH3FA3y+fKSiJ+AmM",
      crossorigin: "anonymous",
    },
  ],

  themes: ["@docusaurus/theme-mermaid"],

  // enable mermaid diagrams and math support
  markdown: {
    mermaid: true,
  },

  themeConfig:
    /** @type {import('@docusaurus/preset-classic').ThemeConfig} */
    {
      navbar: {
        title: "Miden",
        items: [
          {
            href: "https://github.com/0xMiden/",
            label: "GitHub",
            position: "right",
          },
        ],
      },
    },
};

export default config;
