import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Multi-sidebar configuration for Builder and Core Concepts sections
 *
 * - builderSidebar: Usage-focused docs (tutorials, guides, reference)
 *   Canonical source: docs/builder/ (get-started, smart-contracts, etc.)
 *   Ingested content: docs/builder/tutorials/, docs/builder/client/
 *
 * - coreConceptsSidebar: Architecture/internals (protocol, VM, proving)
 *   Canonical source: Landing page in docs/core-concepts/index.md
 *   Ingested content: docs/core-concepts/protocol/, miden-vm/, compiler/, node/
 *
 * ARCHITECTURE NOTE:
 * External docs are ingested at build time via deploy-docs.yml into:
 *   - Core Concepts docs → docs/core-concepts/*
 *   - Builder docs → docs/builder/tutorials/, docs/builder/tools/client/
 * These paths are cleaned and re-synced on each build from source repos.
 */
const sidebars: SidebarsConfig = {
  builderSidebar: [
    // ── GETTING STARTED
    {
      type: "html",
      value: '<span class="sidebar-section">Getting Started</span>',
    },
    { type: "doc", id: "builder/index" },
    {
      type: "category",
      label: "Get Started",
      link: { type: "doc", id: "builder/get-started/index" },
      items: [{ type: "autogenerated", dirName: "builder/get-started" }],
    },

    // ── BUILD
    {
      type: "html",
      value: '<span class="sidebar-section">Build</span>',
    },
    {
      type: "category",
      label: "Smart Contracts",
      link: { type: "doc", id: "builder/smart-contracts/index" },
      items: [
        "builder/smart-contracts/overview",
        {
          type: "category",
          label: "Accounts",
          link: { type: "generated-index", slug: "/builder/smart-contracts/accounts" },
          items: [
            "builder/smart-contracts/accounts/introduction",
            "builder/smart-contracts/accounts/components",
            "builder/smart-contracts/accounts/storage",
            "builder/smart-contracts/accounts/custom-types",
            "builder/smart-contracts/accounts/account-operations",
            "builder/smart-contracts/accounts/cryptography",
            "builder/smart-contracts/accounts/authentication",
          ],
        },
        {
          type: "category",
          label: "Notes",
          link: { type: "generated-index", slug: "/builder/smart-contracts/notes" },
          items: [
            "builder/smart-contracts/notes/introduction",
            "builder/smart-contracts/notes/note-scripts",
            "builder/smart-contracts/notes/note-types",
            "builder/smart-contracts/notes/reading-notes",
            "builder/smart-contracts/notes/output-notes",
          ],
        },
        {
          type: "category",
          label: "Transactions",
          link: { type: "generated-index", slug: "/builder/smart-contracts/transactions" },
          items: [
            "builder/smart-contracts/transactions/introduction",
            "builder/smart-contracts/transactions/transaction-context",
            "builder/smart-contracts/transactions/transaction-scripts",
            "builder/smart-contracts/transactions/advice-provider",
          ],
        },
        "builder/smart-contracts/cross-component-calls",
        "builder/smart-contracts/types",
        "builder/smart-contracts/patterns",
      ],
    },
    {
      type: "category",
      label: "Tutorials",
      link: { type: "doc", id: "builder/tutorials/index" },
      items: [
        "builder/tutorials/miden-bank/index",
        {
          type: "category",
          label: "Recipes",
          collapsed: true,
          items: [
            {
              type: "category",
              label: "Rust",
              link: { type: "doc", id: "builder/tutorials/recipes/rust/index" },
              collapsed: true,
              items: [
                "builder/tutorials/recipes/rust/counter_contract_tutorial",
                "builder/tutorials/recipes/rust/create_deploy_tutorial",
                "builder/tutorials/recipes/rust/mint_consume_create_tutorial",
                "builder/tutorials/recipes/rust/creating_notes_in_masm_tutorial",
                "builder/tutorials/recipes/rust/custom_note_how_to",
                "builder/tutorials/recipes/rust/unauthenticated_note_how_to",
                "builder/tutorials/recipes/rust/mappings_in_masm_how_to",
                "builder/tutorials/recipes/rust/public_account_interaction_tutorial",
                "builder/tutorials/recipes/rust/foreign_procedure_invocation_tutorial",
                "builder/tutorials/recipes/rust/oracle_tutorial",
                "builder/tutorials/recipes/rust/delegated_proving_tutorial",
                "builder/tutorials/recipes/rust/network_transactions_tutorial",
              ],
            },
            {
              type: "category",
              label: "Web / TypeScript",
              link: { type: "doc", id: "builder/tutorials/recipes/web/index" },
              collapsed: true,
              items: [
                // NOTE: "builder/tutorials/recipes/web/setup_guide" lives
                // only on 0xMiden/tutorials#186 (kbg/chore/v14-migration).
                // Re-add once that PR merges into tutorials' main —
                // it'll be part of the v0.14 release branch meanwhile.
                "builder/tutorials/recipes/web/counter_contract_tutorial",
                "builder/tutorials/recipes/web/create_deploy_tutorial",
                "builder/tutorials/recipes/web/mint_consume_create_tutorial",
                "builder/tutorials/recipes/web/creating_multiple_notes_tutorial",
                "builder/tutorials/recipes/web/unauthenticated_note_how_to",
                "builder/tutorials/recipes/web/foreign_procedure_invocation_tutorial",
                "builder/tutorials/recipes/web/react_wallet_tutorial",
              ],
            },
          ],
        },
        {
          type: "category",
          label: "Development helpers",
          collapsed: true,
          items: [
            { type: "autogenerated", dirName: "builder/tutorials/helpers" },
          ],
        },
        "builder/tutorials/miden_node_setup",
      ],
    },
    {
      type: "category",
      label: "Tools",
      link: { type: "doc", id: "builder/tools/index" },
      items: [
        {
          type: "category",
          label: "Clients",
          link: { type: "doc", id: "builder/tools/clients/index" },
          items: [
            {
              type: "category",
              label: "TypeScript",
              link: { type: "doc", id: "builder/tools/clients/web-client/index" },
              items: [
                "builder/tools/clients/web-client/setup",
                "builder/tools/clients/web-client/accounts",
                "builder/tools/clients/web-client/transactions",
                "builder/tools/clients/web-client/notes",
                "builder/tools/clients/web-client/compile",
                "builder/tools/clients/web-client/sync",
                "builder/tools/clients/web-client/testing",
              ],
            },
            {
              type: "category",
              label: "React",
              link: { type: "doc", id: "builder/tools/clients/react-sdk/index" },
              items: [
                "builder/tools/clients/react-sdk/setup",
                "builder/tools/clients/react-sdk/query-hooks",
                "builder/tools/clients/react-sdk/mutation-hooks",
                "builder/tools/clients/react-sdk/advanced",
                "builder/tools/clients/react-sdk/signers",
                "builder/tools/clients/react-sdk/recipes",
              ],
            },
          ],
        },
        "builder/tools/playground",
        "builder/tools/network",
      ],
    },

    // ── SOLUTIONS
    {
      type: "html",
      value: '<span class="sidebar-section">Solutions</span>',
    },
    {
      type: "category",
      label: "Guardian",
      link: { type: "doc", id: "builder/miden-guardian/index" },
      items: [
        {
          type: "category",
          label: "Core Concepts",
          items: [
            "builder/miden-guardian/core-concepts/architecture",
            "builder/miden-guardian/core-concepts/data-structures",
            "builder/miden-guardian/core-concepts/components",
            "builder/miden-guardian/core-concepts/security",
          ],
        },
        {
          type: "category",
          label: "Operator Guide",
          items: [
            "builder/miden-guardian/operator-guide/running",
            "builder/miden-guardian/operator-guide/deployment",
            "builder/miden-guardian/operator-guide/troubleshooting",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Private Multisig",
      link: { type: "doc", id: "builder/private-multisig/index" },
      items: [
        "builder/private-multisig/core-concepts",
        "builder/private-multisig/rust-sdk",
        "builder/private-multisig/typescript-sdk",
      ],
    },

    // ── REFERENCE
    {
      type: "html",
      value: '<span class="sidebar-section">Reference</span>',
    },
    {
      type: "category",
      label: "Migration",
      link: { type: "doc", id: "builder/migration/index" },
      items: [
        "builder/migration/imports-dependencies",
        "builder/migration/hashing-stack",
        "builder/migration/account-changes",
        "builder/migration/note-changes",
        "builder/migration/asset-vault-faucet",
        "builder/migration/transaction-changes",
        "builder/migration/client-changes",
        "builder/migration/masm-changes",
        "builder/migration/vm-assembler",
      ],
    },
    { type: "doc", id: "builder/glossary" },
  ],

  // Core Concepts: landing page + ingested external content
  // Note: External docs are ingested during CI/CD build via deploy-docs.yml
  // For local dev, only the landing page exists; categories appear when content is ingested
  coreConceptsSidebar: [{ type: "autogenerated", dirName: "core-concepts" }],
};

export default sidebars;
