import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Multi-sidebar configuration for Builder and Design sections
 *
 * - builderSidebar: Usage-focused docs (tutorials, guides, reference)
 *   Canonical source: docs/builder/ (quick-start, core-concepts, etc.)
 *   Ingested content: docs/builder/tutorials/, docs/builder/client/
 *
 * - designSidebar: Architecture/internals (protocol, VM, proving)
 *   Canonical source: Landing page in docs/design/index.md
 *   Ingested content: docs/design/miden-base/, miden-vm/, compiler/, miden-node/
 *
 * ARCHITECTURE NOTE:
 * External docs are ingested at build time via deploy-docs.yml into:
 *   - Design docs → docs/design/*
 *   - Builder docs → docs/builder/tutorials/, docs/builder/client/
 * These paths are cleaned and re-synced on each build from source repos.
 */
const sidebars: SidebarsConfig = {
  // Builder: authored content + ingested tutorials/client
  builderSidebar: [{ type: "autogenerated", dirName: "builder" }],

  // Design: landing page + ingested external content
  // Note: External docs are ingested during CI/CD build via deploy-docs.yml
  // For local dev, only the landing page exists; categories appear when content is ingested
  designSidebar: [{ type: "autogenerated", dirName: "design" }],
};

export default sidebars;
