import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// TODO: modify global sidebar to include all vendor links
const sidebars: SidebarsConfig = {
  sidebar: [{ type: "autogenerated", dirName: "." }],

  "miden-node": [{ type: "autogenerated", dirName: "." }],
};

export default sidebars;
