[book]
authors = ["Miden contributors"]
description = "Manual for the Miden compiler"
language = "en"
multilingual = false
title = "The Miden compiler"

[output.html]
git-repository-url = "https://github.com/0xMiden/compiler"

[preprocessor.katex]
after = ["links"]

[preprocessor.alerts]

[output.linkcheck]
exclude = ['[!][A-Z]*']
