name: Update Documentation

# Schedule the workflow to run at 00:00 UTC every day
on:
  schedule:
    - cron: '* * * * *'  # Adjust the cron expression as needed

jobs:
  update-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for accurate change detection

      - name: Set Up Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      - name: Run Update Script
        run: |
          chmod +x ./update_docs.sh
          ./update_docs.sh

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add -A
          if git diff --cached --quiet; then
            echo "No changes detected."
          else
            git commit -m "Automated update of documentation"
            git push origin HEAD:${{ github.ref }}
          fi
