name: update documentation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: # Allow manual triggering for testing

jobs:
  update-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Grant write access to the repository

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }} # Important: use token for checkout

      - name: Set Up Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      - name: Run Update Script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Pass token to script if needed
        run: ./scripts/update_docs.sh

      - name: Commit and Push Changes
        run: |
          git add -A
          if git diff --cached --quiet; then
            echo "No changes detected."
          else
            git commit -m "Automated update of documentation"
            git push origin main  # Explicitly specify the branch
          fi